services:
  updater-cli-args:
    image: eigenlayer-rewards-updater:latest
    build:
      dockerfile: Dockerfile
    command:
      - "updater"
      - "--debug=true"
      - "--enable-statsd=false"
      - "--enable-tracing=false"
      - "--environment=testnet"
      - "--network=holesky"
      - "--rpc-url=https://ethereum-holesky-rpc.publicnode.com"
      - "--proof-store-base-url=https://eigenlabs-rewards-testnet-holesky.s3.amazonaws.com"
      - "--private-key=<ethereum private key (hex string, not prefixed with 0x)>"
      - "--rewards-coordinator-address=0xAcc1fb458a1317E886dB376Fc8141540537E68fE"
