// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	rewards "github.com/Layr-Labs/protocol-apis/gen/protos/eigenlayer/sidecar/v1/rewards"
)

// IRewardsClient is an autogenerated mock type for the IRewardsClient type
type IRewardsClient struct {
	mock.Mock
}

// GenerateRewards provides a mock function with given fields: ctx, req, opts
func (_m *IRewardsClient) GenerateRewards(ctx context.Context, req *rewards.GenerateRewardsRequest, opts ...grpc.CallOption) (*rewards.GenerateRewardsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRewards")
	}

	var r0 *rewards.GenerateRewardsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rewards.GenerateRewardsRequest, ...grpc.CallOption) (*rewards.GenerateRewardsResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rewards.GenerateRewardsRequest, ...grpc.CallOption) *rewards.GenerateRewardsResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rewards.GenerateRewardsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rewards.GenerateRewardsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateRewardsRoot provides a mock function with given fields: ctx, req, opts
func (_m *IRewardsClient) GenerateRewardsRoot(ctx context.Context, req *rewards.GenerateRewardsRootRequest, opts ...grpc.CallOption) (*rewards.GenerateRewardsRootResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRewardsRoot")
	}

	var r0 *rewards.GenerateRewardsRootResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rewards.GenerateRewardsRootRequest, ...grpc.CallOption) (*rewards.GenerateRewardsRootResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rewards.GenerateRewardsRootRequest, ...grpc.CallOption) *rewards.GenerateRewardsRootResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rewards.GenerateRewardsRootResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rewards.GenerateRewardsRootRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRewardsClient creates a new instance of IRewardsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRewardsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRewardsClient {
	mock := &IRewardsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
