// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	proofDataFetcher "github.com/Layr-Labs/eigenlayer-payment-updater/pkg/proofDataFetcher"
	mock "github.com/stretchr/testify/mock"
)

// ProofDataFetcher is an autogenerated mock type for the ProofDataFetcher type
type ProofDataFetcher struct {
	mock.Mock
}

// FetchClaimAmountsForDate provides a mock function with given fields: date
func (_m *ProofDataFetcher) FetchClaimAmountsForDate(date string) (*proofDataFetcher.PaymentProofData, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FetchClaimAmountsForDate")
	}

	var r0 *proofDataFetcher.PaymentProofData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*proofDataFetcher.PaymentProofData, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(string) *proofDataFetcher.PaymentProofData); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proofDataFetcher.PaymentProofData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchLatestSnapshot provides a mock function with given fields:
func (_m *ProofDataFetcher) FetchLatestSnapshot() (*proofDataFetcher.Snapshot, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchLatestSnapshot")
	}

	var r0 *proofDataFetcher.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func() (*proofDataFetcher.Snapshot, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *proofDataFetcher.Snapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proofDataFetcher.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRecentSnapshotList provides a mock function with given fields:
func (_m *ProofDataFetcher) FetchRecentSnapshotList() ([]*proofDataFetcher.Snapshot, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchRecentSnapshotList")
	}

	var r0 []*proofDataFetcher.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*proofDataFetcher.Snapshot, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*proofDataFetcher.Snapshot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proofDataFetcher.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProofDataFetcher creates a new instance of ProofDataFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProofDataFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProofDataFetcher {
	mock := &ProofDataFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
