// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	paymentCoordinator "github.com/Layr-Labs/eigenlayer-payment-proofs/pkg/paymentCoordinator"
	mock "github.com/stretchr/testify/mock"
)

// Transactor is an autogenerated mock type for the Transactor type
type Transactor struct {
	mock.Mock
}

// CurrPaymentCalculationEndTimestamp provides a mock function with given fields:
func (_m *Transactor) CurrPaymentCalculationEndTimestamp() (uint32, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CurrPaymentCalculationEndTimestamp")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint32, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentCoordinator provides a mock function with given fields:
func (_m *Transactor) GetPaymentCoordinator() *paymentCoordinator.ContractIPaymentCoordinator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentCoordinator")
	}

	var r0 *paymentCoordinator.ContractIPaymentCoordinator
	if rf, ok := ret.Get(0).(func() *paymentCoordinator.ContractIPaymentCoordinator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paymentCoordinator.ContractIPaymentCoordinator)
		}
	}

	return r0
}

// GetRootIndex provides a mock function with given fields: root
func (_m *Transactor) GetRootIndex(root [32]byte) (uint32, error) {
	ret := _m.Called(root)

	if len(ret) == 0 {
		panic("no return value specified for GetRootIndex")
	}

	var r0 uint32
	var r1 error
	if rf, ok := ret.Get(0).(func([32]byte) (uint32, error)); ok {
		return rf(root)
	}
	if rf, ok := ret.Get(0).(func([32]byte) uint32); ok {
		r0 = rf(root)
	} else {
		r0 = ret.Get(0).(uint32)
	}

	if rf, ok := ret.Get(1).(func([32]byte) error); ok {
		r1 = rf(root)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitRoot provides a mock function with given fields: ctx, root, paymentsUnixTimestamp
func (_m *Transactor) SubmitRoot(ctx context.Context, root [32]byte, paymentsUnixTimestamp uint32) error {
	ret := _m.Called(ctx, root, paymentsUnixTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for SubmitRoot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [32]byte, uint32) error); ok {
		r0 = rf(ctx, root, paymentsUnixTimestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactor creates a new instance of Transactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactor {
	mock := &Transactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
