// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	contractIPaymentCoordinator "github.com/Layr-Labs/eigenlayer-payment-updater/bindings/IPaymentCoordinator"
	mock "github.com/stretchr/testify/mock"
)

// PaymentsDataService is an autogenerated mock type for the PaymentsDataService type
type PaymentsDataService struct {
	mock.Mock
}

// GetLatestRootSubmission provides a mock function with given fields: ctx
func (_m *PaymentsDataService) GetLatestRootSubmission(ctx context.Context) ([32]byte, *big.Int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRootSubmission")
	}

	var r0 [32]byte
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([32]byte, *big.Int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) [32]byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *big.Int); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRangePaymentsWithOverlappingRange provides a mock function with given fields: startTimestamp, endTimestamp
func (_m *PaymentsDataService) GetRangePaymentsWithOverlappingRange(startTimestamp *big.Int, endTimestamp *big.Int) ([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment, error) {
	ret := _m.Called(startTimestamp, endTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetRangePaymentsWithOverlappingRange")
	}

	var r0 []*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) ([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment, error)); ok {
		return rf(startTimestamp, endTimestamp)
	}
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) []*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment); ok {
		r0 = rf(startTimestamp, endTimestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int, *big.Int) error); ok {
		r1 = rf(startTimestamp, endTimestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentsDataService creates a new instance of PaymentsDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentsDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentsDataService {
	mock := &PaymentsDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
