environment: mainnet
network: ethereum
cronJob:
  namespace: mainnet-ethereum
  enabled: false
  image:
    tag: v1.0.0-rc.3
claimJob:
  namespace: testnet-holesky
  enabled: false
  image:
    tag: v1.0.0-rc.3
verifyRootJob:
  enabled: true
  image:
    tag: v1.0.0-rc.3
  config: |
    debug: true
    
    environment: "mainnet"
    network: "ethereum"
    rpc_url: "https://ethereum-rpc.publicnode.com"
    proof_store_base_url: "https://eigenlabs-rewards-mainnet-ethereum.s3.amazonaws.com"
    private_key: "c4d8ec6c8f3224aabc3335e088a168c75db6d5c284bedc01bdb550d7362a59d8"
    rewards_coordinator_address: "0x7750d328b314effa365a0402ccfd489b80b0adda"

rewardsDataJob:
  name: rewards-data
  enabled: true
  sidecarUrl: "sidecar.blocklake-mainnet-ethereum.svc.cluster.local:7100"
