// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	big "math/big"

	distribution "github.com/Layr-Labs/eigenlayer-payment-updater/common/distribution"

	mock "github.com/stretchr/testify/mock"
)

// DistributionDataService is an autogenerated mock type for the DistributionDataService type
type DistributionDataService struct {
	mock.Mock
}

// GetDistributionAtTimestamp provides a mock function with given fields: timestamp
func (_m *DistributionDataService) GetDistributionAtTimestamp(timestamp *big.Int) (*distribution.Distribution, error) {
	ret := _m.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetDistributionAtTimestamp")
	}

	var r0 *distribution.Distribution
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int) (*distribution.Distribution, error)); ok {
		return rf(timestamp)
	}
	if rf, ok := ret.Get(0).(func(*big.Int) *distribution.Distribution); ok {
		r0 = rf(timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*distribution.Distribution)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDistributionAtTimestamp provides a mock function with given fields: timestamp, distributions
func (_m *DistributionDataService) SetDistributionAtTimestamp(timestamp *big.Int, distributions *distribution.Distribution) error {
	ret := _m.Called(timestamp, distributions)

	if len(ret) == 0 {
		panic("no return value specified for SetDistributionAtTimestamp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*big.Int, *distribution.Distribution) error); ok {
		r0 = rf(timestamp, distributions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDistributionDataService creates a new instance of DistributionDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDistributionDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DistributionDataService {
	mock := &DistributionDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
