// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	eigenlayer_payment_updatercommon "github.com/Layr-Labs/eigenlayer-payment-updater/common"

	mock "github.com/stretchr/testify/mock"
)

// OperatorSetDataService is an autogenerated mock type for the OperatorSetDataService type
type OperatorSetDataService struct {
	mock.Mock
}

// GetBlockNumberAtTimestamp provides a mock function with given fields: timestamp
func (_m *OperatorSetDataService) GetBlockNumberAtTimestamp(timestamp *big.Int) (*big.Int, error) {
	ret := _m.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockNumberAtTimestamp")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int) (*big.Int, error)); ok {
		return rf(timestamp)
	}
	if rf, ok := ret.Get(0).(func(*big.Int) *big.Int); ok {
		r0 = rf(timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int) error); ok {
		r1 = rf(timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperatorSetForStrategyAtTimestamp provides a mock function with given fields: timestamp, avs, strategy
func (_m *OperatorSetDataService) GetOperatorSetForStrategyAtTimestamp(timestamp *big.Int, avs common.Address, strategy common.Address) (*eigenlayer_payment_updatercommon.OperatorSet, error) {
	ret := _m.Called(timestamp, avs, strategy)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorSetForStrategyAtTimestamp")
	}

	var r0 *eigenlayer_payment_updatercommon.OperatorSet
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int, common.Address, common.Address) (*eigenlayer_payment_updatercommon.OperatorSet, error)); ok {
		return rf(timestamp, avs, strategy)
	}
	if rf, ok := ret.Get(0).(func(*big.Int, common.Address, common.Address) *eigenlayer_payment_updatercommon.OperatorSet); ok {
		r0 = rf(timestamp, avs, strategy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eigenlayer_payment_updatercommon.OperatorSet)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int, common.Address, common.Address) error); ok {
		r1 = rf(timestamp, avs, strategy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOperatorSetDataService creates a new instance of OperatorSetDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperatorSetDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperatorSetDataService {
	mock := &OperatorSetDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
