// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	big "math/big"

	context "context"

	contractIPaymentCoordinator "github.com/Layr-Labs/eigenlayer-payment-updater/bindings/IPaymentCoordinator"

	mock "github.com/stretchr/testify/mock"
)

// PaymentCalculatorDataService is an autogenerated mock type for the PaymentCalculatorDataService type
type PaymentCalculatorDataService struct {
	mock.Mock
}

// GetPaymentsCalculatedUntilTimestamp provides a mock function with given fields: ctx
func (_m *PaymentCalculatorDataService) GetPaymentsCalculatedUntilTimestamp(ctx context.Context) (*big.Int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsCalculatedUntilTimestamp")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRangePaymentsWithOverlappingRange provides a mock function with given fields: startTimestamp, endTimestamp
func (_m *PaymentCalculatorDataService) GetRangePaymentsWithOverlappingRange(startTimestamp *big.Int, endTimestamp *big.Int) ([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment, error) {
	ret := _m.Called(startTimestamp, endTimestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetRangePaymentsWithOverlappingRange")
	}

	var r0 []*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment
	var r1 error
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) ([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment, error)); ok {
		return rf(startTimestamp, endTimestamp)
	}
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) []*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment); ok {
		r0 = rf(startTimestamp, endTimestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*contractIPaymentCoordinator.IPaymentCoordinatorRangePayment)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int, *big.Int) error); ok {
		r1 = rf(startTimestamp, endTimestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentCalculatorDataService creates a new instance of PaymentCalculatorDataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentCalculatorDataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentCalculatorDataService {
	mock := &PaymentCalculatorDataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
