---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronJob.name }}
  namespace: {{ .Values.cronJob.namespace }}
  labels:
    app: {{ .Values.cronJob.name }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: payment-updater
              image: {{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}
              imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
              args:
                - "updater"
              volumeMounts:
                - name: config-volume
                  mountPath: "/etc/eigenlayer-payment-updater/"
                  readOnly: true
          volumes:
            - name: config-volume
              secret:
                secretName: {{ .Values.cronJob.name }}-secret
