{{- if eq .Values.claimJob.enabled true -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.claimJob.name }}-secret
type: Opaque
data:
  config.yml: {{ .Values.claimJob.config | b64enc | quote }}
{{- end -}}
