{{- if eq .Values.verifyRootJob.enabled true -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.verifyRootJob.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/version: {{ .Values.version }}
    tags.datadoghq.com/service: "{{ .Values.verifyRootJob.name }}"
    admission.datadoghq.com/config.mode: "socket"
    app: {{ .Values.verifyRootJob.name }}
spec:
  schedule: "{{ .Values.verifyRootJob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            tags.datadoghq.com/env: {{ .Values.environment }}
            tags.datadoghq.com/version: {{ .Values.version }}
            tags.datadoghq.com/service: "{{ .Values.verifyRootJob.name }}"
            admission.datadoghq.com/enabled: "true"
        spec:
          restartPolicy: Never
          containers:
            - name: rewards-updater
              image: {{ .Values.verifyRootJob.image.repository }}:{{ .Values.verifyRootJob.image.tag }}
              imagePullPolicy: {{ .Values.verifyRootJob.image.pullPolicy }}
              args:
                - "claim"
              volumeMounts:
                - name: config-volume
                  mountPath: "/etc/eigenlayer-rewards-updater/"
                  readOnly: true
              env:
                - name: DD_TRACE_SAMPLE_RATE
                  value: "1.0"
          volumes:
            - name: config-volume
              secret:
                secretName: {{ .Values.verifyRootJob.name }}-secret

{{- end -}}
