cronJob:
  name: eigenlayer-payment-updater
  namespace: default
  schedule: "*/15 * * * *"    # Runs every 15 minutes looking for new roots to post
  image:
    repository: 225727539677.dkr.ecr.us-east-1.amazonaws.com/eigenlayer-payment-updater
    tag: latest
    pullPolicy: Always
  config: |
    debug: true
  
    environment: ""
    network: ""
    rpc_url: "https://eigenpayments-dev.s3.us-east-2.amazonaws.com"
    private_key: ""
    payment_coordinator_address: ""
