package utils

const (
	TEST_SUBGRAPH_CLAIMING_MANAGER    = SUBGRAPH_CLAIMING_MANAGER + "-test"
	TEST_SUBGRAPH_PAYMENT_COORDINATOR = SUBGRAPH_PAYMENT_COORDINATOR + "-test"
	TEST_SUBGRAPH_DELEGATION_MANAGER  = SUBGRAPH_DELEGATION_MANAGER + "-test"
)
